/** Exact English → simple Gujarati. Proper names stay English via KEEP in tr-gu. */
export const PHRASES: Record<string, string> = {
  // landing
  "Open sample plant": "નમૂના પ્લાન્ટ ખોલો",
  "Open a sample plant — free": "નમૂના પ્લાન્ટ ખોલો — મફત",
  "For the owner who counts every rupee": "જે માલિક દરેક રૂપિયો ગણે છે તેના માટે",
  "If the plant stops for": "જો પ્લાન્ટ બંધ રહે",
  "days, you already paid for Urja.": "દિવસ, તમે પહેલેથી ઉર્જાના પૈસા ભરી દીધા.",
  "Urja is": "ઉર્જા છે",
  "a month. One dead day of gas is": "મહિને. ગેસનો એક મરેલો દિવસ છે",
  "One sour tank is": "એક ખાટી ટાંકી છે",
  "You are not buying an app. You are buying that these holes stay shut.":
    "તમે એપ નથી ખરીદતા. તમે ખરીદો છો કે આ છિદ્રો બંધ રહે.",
  "every month": "દર મહિને",
  "a month": "મહિને",
  "Plant stops 1 day": "પ્લાન્ટ ૧ દિવસ બંધ",
  "gas you did not sell": "ગેસ જે વેચ્યો નહીં",
  "One tank dies": "એક ટાંકી મરે",
  "months of Urja": "મહિના ઉર્જા",
  "Show me the holes": "મને છિદ્રો બતાવો",
  "No card. No salesman on the first click. You look. Then you decide.":
    "કાર્ડ નહીં. પહેલા ક્લિક પર સેલ્સમેન નહીં. તમે જુઓ. પછી નક્કી કરો.",
  "These holes are already in the plant. Registers do not show them.":
    "આ છિદ્રો પ્લાન્ટમાં પહેલેથી છે. રજિસ્ટરમાં દેખાતા નથી.",
  "A tight owner pays when the hole is bigger than the fee. Count with us.":
    "કડક માલિક ત્યારે પૈસા આપે જ્યારે છિદ્ર ફી કરતાં મોટું હોય. સાથે ગણો.",
  "If the line stops for 1 day": "લાઈન ૧ દિવસ બંધ રહે તો",
  "No dung, no gas, no bill. That one day is already most of the monthly fee.":
    "ગોબર નહીં, ગેસ નહીં, બિલ નહીં. એ એક દિવસ મહિનાની ફીનો મોટો ભાગ છે.",
  "Gas cleaning waste · every month": "ગેસ સાફ કરતાં વેડફાટ · દર મહિને",
  "Dirty gas going out the pipe. You cannot see it in a register. It is already more than ₹75,000.":
    "ગંદો ગેસ પાઈપમાંથી નીકળે. રજિસ્ટરમાં ન દેખાય. પહેલેથી ₹૭૫,૦૦૦થી વધુ છે.",
  "Wrong mix of dung and grass · every month": "ગોબર અને ઘાસનું ખોટું મિક્સ · દર મહિને",
  "Same trucks, less gas. The extra you did not make is 2–3 times the fee.":
    "એ જ ટ્રક, ઓછો ગેસ. જે વધારો ન બન્યો તે ફી કરતાં ૨–૩ ગણો છે.",
  "One tank goes sour · about 3 weeks": "એક ટાંકી ખાટી થાય · લગભગ ૩ અઠવાડિયા",
  "That one crash is more than a year of Urja. Yellow warning is cheaper than a dead tank.":
    "એ એક ક્રેશ ઉર્જાના એક વર્ષથી વધુ છે. પીળી ચેતવણી મરેલી ટાંકી કરતાં સસ્તી.",
  "Customers holding your money · right now": "ગ્રાહકો તમારા પૈસા પકડી રાખે · અત્યારે",
  "Not profit. Not sales. Money that is yours, sitting in their pocket.":
    "નફો નહીં. વેચાણ નહીં. તમારા પૈસા, તેમની જેબમાં પડ્યા છે.",
  "When does ₹75,000 come back?": "₹૭૫,૦૦૦ ક્યારે પાછા આવે?",
  "Only the gas cleaner is wasting": "ફક્ત ગેસ ક્લીનર વેડફે છે",
  "days": "દિવસ",
  "/ month going out the pipe": "/ મહિને પાઈપમાંથી નીકળે",
  "Dung mix is a bit wrong": "ગોબર મિક્સ થોડું ખોટું છે",
  "/ month extra gas you did not make": "/ મહિને વધારાનો ગેસ જે ન બન્યો",
  "Line stops once": "લાઈન એક વાર બંધ",
  "of CBG not sold": "CBG વેચાયો નહીં",
  "One tank goes sour": "એક ટાંકી ખાટી થાય",
  "months paid": "મહિના ભર્યા",
  "gone in ~3 weeks": "~૩ અઠવાડિયામાં ગયા",
  "If we sit at your plant and cannot show a hole bigger than":
    "જો તમારા પ્લાન્ટે બેસીને ફી કરતાં મોટું છિદ્ર ન બતાવી શકીએ",
  "do not pay. Keep your money.": "પૈસા ન આપો. તમારા પૈસા રાખો.",
  "You stay the boss. Staff cannot empty the pocket.":
    "માલિક તમે રહો. સ્ટાફ જેબ ખાલી ન કરી શકે.",
  "You tick big money": "મોટા પૈસા પર તમે ટિક કરો",
  "Buy over ₹10,000, salary advance, extra discount — nothing goes until you say yes on the phone.":
    "₹૧૦,૦૦૦થી વધુ ખરીદી, પગાર એડવાન્સ, વધારાની છૂટ — તમે ફોન પર હા કહો ત્યાં સુધી કંઈ ન ચાલે.",
  "Store girl can run it": "સ્ટોરની બહેન ચલાવી શકે",
  "Green = fine. Yellow = look. Red = stop. No English essay. WhatsApp OTP. Same as the phone they already use.":
    "લીલું = ઠીક. પીળું = જુઓ. લાલ = રોકો. અંગ્રેજી નિબંધ નહીં. વોટ્સએપ OTP. જે ફોન વપરાય છે તે જ.",
  "Truck short? Pay less": "ટ્રક ઓછી? ઓછા પૈસા આપો",
  "Ordered 40 t, got 38.4 t — the page says pay for 38.4. Paper books miss this. That is how money leaves.":
    "૪૦ ટન મંગાવ્યા, ૩૮.૪ મળ્યા — પેજ કહે ૩૮.૪ના પૈસા આપો. કાગળની ચોપડી આ ચૂકે. આ રીતે પૈસા નીકળે.",
  "How a tight owner buys this": "કડક માલિક આ કેવી રીતે ખરીદે",
  "Open the sample plant today": "આજે નમૂના પ્લાન્ટ ખોલો",
  "Click once. See money stuck, stock that will stop the line, tank going yellow. Two minutes. No form.":
    "એક ક્લિક. અટકેલા પૈસા, લાઈન રોકે તેવો સ્ટોક, પીળી થતી ટાંકી. બે મિનિટ. ફોર્મ નહીં.",
  "We come to YOUR plant": "અમે તમારા પ્લાન્ટે આવીએ",
  "We put YOUR trucks, YOUR dues, YOUR tanks on the same pages. If the holes are smaller than ₹75,000, you walk away.":
    "તમારી ટ્રક, તમારા બાકી, તમારી ટાંકી એ જ પેજ પર. છિદ્રો ₹૭૫,૦૦૦થી નાના હોય તો ચાલ્યા જાઓ.",
  "Start with what you already write": "જે પહેલેથી લખો છો તેથી શરૂ",
  "No new machine on day one. Godown, bills, staff. Sensors later — only if you want them.":
    "પહેલા દિવસે નવું મશીન નહીં. ગોડાઉન, બિલ, સ્ટાફ. સેન્સર પછી — જો તમે જોઈએ.",
  "What it costs": "શું ખર્ચ",
  "a month for the full plant. One number. Smaller factory without tanks is ₹20,000. Carbon papers — later, only if that money is real.":
    "પૂરા પ્લાન્ટ માટે મહિને. એક આંકડો. ટાંકી વગરની નાની ફેક્ટરી ₹૨૦,૦૦૦. કાર્બન કાગળ — પછી, જો પૈસા સાચા હોય.",
  "See it on a real plant screen": "અસલ પ્લાન્ટ સ્ક્રીન પર જુઓ",
  "Come. Show the holes on my plant. Then I decide.":
    "આવો. મારા પ્લાન્ટ પર છિદ્રો બતાવો. પછી હું નક્કી કરું.",
  "Free visit. You do not pay ₹75,000 to have a look. You pay after you see your own numbers.":
    "મફત મુલાકાત. જોવા માટે ₹૭૫,૦૦૦ નહીં. તમારા આંકડા જોયા પછી પૈસા આપો.",
  "We will call you": "અમે તમને ફોન કરીશું",
  "Keep your phone on. We only come to count holes — not to push papers.":
    "ફોન ચાલુ રાખો. અમે છિદ્રો ગણવા આવીએ — કાગળ ઘસવા નહીં.",
  "Meanwhile, open the sample plant →": "ત્યાં સુધી નમૂના પ્લાન્ટ ખોલો →",
  "Ask us to come": "અમને આવવાનું કહો",
  "Your name": "તમારું નામ",
  "Plant / factory name": "પ્લાન્ટ / ફેક્ટરીનું નામ",
  "Phone (WhatsApp)": "ફોન (વોટ્સએપ)",
  "City": "શહેર",
  "Call me. Show the holes.": "મને ફોન કરો. છિદ્રો બતાવો.",
  "/ month · full plant": "/ મહિને · પૂરો પ્લાન્ટ",

  // login
  "See the holes. Then decide on ₹75,000.": "છિદ્રો જુઓ. પછી ₹૭૫,૦૦૦ પર નક્કી કરો.",
  "Open as the owner. In two minutes you should see late money, stock that can stop the line, and spends waiting for your yes.":
    "માલિક તરીકે ખોલો. બે મિનિટમાં મોડા પૈસા, લાઈન રોકે તેવો સ્ટોક, અને તમારી હા માટે રાહ જોતા ખર્ચ દેખાય.",
  "Green = all fine": "લીલું = બધું ઠીક",
  "Yellow = look today": "પીળું = આજે જુઓ",
  "Red = money can leave": "લાલ = પૈસા નીકળી શકે",
  "₹75,000 / month · full plant · you tick big spends":
    "₹૭૫,૦૦૦ / મહિને · પૂરો પ્લાન્ટ · મોટા ખર્ચ પર તમે ટિક",
  "Open the sample plant": "નમૂના પ્લાન્ટ ખોલો",
  "No payment. Look at the holes. Then decide.": "પેમેન્ટ નહીં. છિદ્રો જુઓ. પછી નક્કી કરો.",
  "I am the owner — show me the holes": "હું માલિક છું — છિદ્રો બતાવો",
  "Big button. One tap. See late money first.": "મોટું બટન. એક ટેપ. પહેલા મોડા પૈસા જુઓ.",
  "Already have a login": "પહેલેથી લોગિન છે",
  "Phone OTP": "ફોન OTP",
  "Phone number": "ફોન નંબર",
  "OTP code": "OTP કોડ",
  "Any 6 digits for demo": "ડેમો માટે કોઈ પણ ૬ અંક",
  "Send OTP": "OTP મોકલો",
  "Enter plant": "પ્લાન્ટમાં જાઓ",
  "Password": "પાસવર્ડ",
  "Other people": "બીજા લોકો",
  "Late money, stock that can stop you, your yes on spends":
    "મોડા પૈસા, સ્ટોક જે તમને રોકે, ખર્ચ પર તમારી હા",
  "See tanks, trucks, warnings — daily plant work":
    "ટાંકી, ટ્રક, ચેતવણી જુઓ — રોજનું પ્લાન્ટ કામ",
  "Only look at proof & papers — cannot change":
    "ફક્ત પુરાવો અને કાગળ જુઓ — બદલી શકાય નહીં",
  "See all client plants": "બધા ક્લાયન્ટ પ્લાન્ટ જુઓ",
  "Only stock, PO, GRN — not sales or salary":
    "ફક્ત સ્ટોક, PO, GRN — વેચાણ કે પગાર નહીં",
  "Only making goods and quality checks": "ફક્ત માલ બનાવવો અને ક્વોલિટી ચેક",
  "Only customers, bills, and who owes money":
    "ફક્ત ગ્રાહક, બિલ, અને કોણ પૈસા દેવું છે",
  "Bills, supplier pay, money snapshot — no HR edit":
    "બિલ, સપ્લાયર પે, પૈસાનો સ્નેપશોટ — HR ફેરફાર નહીં",
  "Only staff, leave, salary": "ફક્ત સ્ટાફ, રજા, પગાર",
  "Only my attendance, jobs, payslip, leave":
    "ફક્ત મારી હાજરી, કામ, પગાર સ્લિપ, રજા",
  "My trips, working days, monthly pay + trip extra":
    "મારી ટ્રિપ, કામના દિવસ, મહિનાનો પગાર + ટ્રિપ વધારો",
  "Lab samples and burnt-gas log — prove if a tank is sick":
    "લેબ સેમ્પલ અને બળેલા ગેસની નોંધ — ટાંકી બીમાર છે કે નહીં",
  "Lab · samples, D2 acids, burnt gas": "લેબ · સેમ્પલ, D2 એસિડ, બળેલો ગેસ",
  "Truck driver · days, trips, monthly pay": "ટ્રક ડ્રાઈવર · દિવસ, ટ્રિપ, મહિનાનો પગાર",
  "Hide other desks": "બીજી ડેસ્ક છુપાવો",
  "More desks (store, drivers, HR…)": "વધુ ડેસ્ક (સ્ટોર, ડ્રાઈવર, HR…)",
  "Purification · floor": "શુદ્ધિકરણ · ફ્લોર",
  "Residue truck": "અવશેષ ટ્રક",

  // onboarding
  "First setup — 4 easy steps": "પહેલી સેટઅપ — ૪ સહેલા પગલાં",
  "Tell Urja about your plant once. Then every page already knows your story.":
    "એક વાર ઉર્જાને પ્લાન્ટ વિશે કહો. પછી દરેક પેજ તમારી વાત જાણે.",
  "Four short steps: plant, carbon path, sensors, team. Then you are ready.":
    "ચાર નાના પગલાં: પ્લાન્ટ, કાર્બન પાથ, સેન્સર, ટીમ. પછી તૈયાર.",
  "Plant birth certificate": "પ્લાન્ટનું જન્મ પ્રમાણપત્ર",
  "Plant basics": "પ્લાન્ટની મૂળ વાત",
  "Where & how big": "ક્યાં અને કેટલું મોટું",
  "Carbon path": "કાર્બન પાથ",
  "Which market pays": "કયું બજાર પૈસા આપે",
  "Link sensors": "સેન્સર જોડો",
  "Trust the numbers": "આંકડા પર વિશ્વાસ",
  "Invite team": "ટીમને બોલાવો",
  "Who sees what": "કોણ શું જુએ",
  "Loading…": "ખુલે છે…",
  "Map pin · 19.85°N, 74.00°E — used later to check truck GPS":
    "નકશાની પિન · 19.85°N, 74.00°E — પછી ટ્રક GPS ચેક માટે",
  "This choice shapes your auditor papers and carbon money words.":
    "આ પસંદગી ચેકરના કાગળ અને કાર્બન પૈસાની ભાષા બદલે.",
  "India carbon market path": "ભારત કાર્બન માર્કેટ પાથ",
  "International credit path": "આંતરરાષ્ટ્રીય ક્રેડિટ પાથ",
  "Premium co-benefit path": "પ્રીમિયમ સાથેના ફાયદાનો પાથ",
  "Gold Standard": "ગોલ્ડ સ્ટાન્ડર્ડ",
  "Link sensor kits so tank health has real machine numbers.":
    "સેન્સર કિટ જોડો કે ટાંકીની તબિયત પાસે અસલ મશીન આંકડા હોય.",
  "QR scanner — aim at tank kit label": "QR સ્કેનર — ટાંકી કિટ લેબલ પર મારો",
  "Simulate successful scan": "સફળ સ્કેન ચલાવો",
  "Operators get floor pages. Auditors get proof locker + papers — view only.":
    "ઓપરેટરને ફ્લોર પેજ. ચેકરને પુરાવા લોકર + કાગળ — ફક્ત જોવું.",
  "Tip: invite your auditor now — they land in Proof locker, not billing.":
    "ટીપ: હવે ચેકરને બોલાવો — તેઓ પુરાવા લોકરમાં જાય, બિલિંગમાં નહીં.",
  "Open morning page": "સવારનું પેજ ખોલો",
  "Continue": "આગળ",
  "Back": "પાછા",

  // book + chrome
  "Put in by": "લખનાર",
  "This seat cannot write this. Need": "આ સીટ આ લખી શકે નહીં. જોઈએ",
  "You are": "તમે છો",
  "From another desk": "બીજી ડેસ્કથી",
  "Also on the change log.": "ફેરફારની નોંધમાં પણ.",
  "Also on the change log": "ફેરફારની નોંધમાં પણ",
  "Nothing here": "અહીં કંઈ નથી",
  "Green = safe · Yellow = careful · Red = problem":
    "લીલું = સલામત · પીળું = સાવધ · લાલ = મુશ્કેલી",
  "Good": "સારું",
  "Ordered": "મંગાવ્યું",
  "Got": "મળ્યું",
  "Like": "એટલે કે",
  "Now": "અત્યારે",
  "more — extra money": "વધુ — વધારાના પૈસા",
  "Plant": "પ્લાન્ટ",
  "CI score": "CI સ્કોર",

  // dashboard / tiles
  "Your money, still with customers": "તમારા પૈસા, હજુ ગ્રાહકો પાસે",
  "Not in your bank yet · drag to move": "હજુ બેંકમાં નથી · ખસેડવા ખેંચો",
  "Late — call today": "મોડું — આજે ફોન કરો",
  "Past the due date · drag to move": "તારીખ નીકળી ગઈ · ખસેડવા ખેંચો",
  "Gas wasted today": "આજે વેડફાયેલો ગેસ",
  "Waiting for your yes": "તમારી હા માટે રાહ",
  "Staff cannot spend till you tick": "તમે ટિક કરો ત્યાં સુધી સ્ટાફ ખર્ચ ન કરે",
  "Staff cannot spend this until you tick.": "તમે ટિક કરો ત્યાં સુધી સ્ટાફ આ ખર્ચ ન કરે.",
  "In 30 days this is more than": "૩૦ દિવસમાં આ વધુ છે",

  // person desk
  "here since": "અહીંથી",
  "reports to": "રિપોર્ટ",
  "Present": "હાજર",
  "Late": "મોડા",
  "Absent": "ગેરહાજર",
  "Off": "છુટ્ટી",
  "Ask leave": "રજા માગો",
  "Asked from My card": "મારા કાર્ડથી માગ્યું",
  "Leave asked. It is on Staff for HR / Owner to tick — and on the change log.":
    "રજા માગી. સ્ટાફ પર HR / માલિકની ટિક માટે છે — અને ફેરફારની નોંધમાં.",
  "Leave on this card": "આ કાર્ડ પર રજા",
  "Waiting for HR": "HRની રાહ",
  "Allowed": "મંજૂર",
  "Jobs assigned to you": "તમને આપેલા કામ",
  "Mark done": "પૂરું કરો",
  "Working days this month": "આ મહિનાના કામના દિવસ",
  "This month’s money": "આ મહિનાના પૈસા",
  "Pay day": "પગારનો દિવસ",
  "Week 1": "અઠવાડિયું ૧",
  "Week 2": "અઠવાડિયું ૨",
  "Week 3": "અઠવાડિયું ૩",
  "Advance cut": "એડવાન્સ કાપ",
  "Cuts": "કાપ",
  "Monthly": "મહિનાનું",
  "day(s)": "દિવસ",
  "today in": "આજે આવ્યા",

  // trucks
  "Village": "ગામ",
  "On road": "રસ્તે",
  "Gate": "ગેટ",
  "Weighbridge": "વેબ્રિજ",
  "Still loading. No photo, no weight — do not pay the farmer.":
    "હજુ લોડ થાય છે. ફોટો નહીં, વજન નહીં — ખેડૂતને પૈસા ન આપો.",
  "Trip not finished. Farmer pay waits for the weighbridge.":
    "ટ્રિપ પૂરી નથી. ખેડૂતના પૈસા વેબ્રિજની રાહ જુએ.",
  "Finish the pad. Do not ask Accounts for August salary today.":
    "પેડ પૂરું કરો. આજે એકાઉન્ટ્સને ઓગસ્ટ પગાર ન માગો.",
  "Pay the farmer for this trip. Do not pay August salary from here — that is 7 Sep.":
    "આ ટ્રિપના ખેડૂતને પૈસા આપો. અહીંથી ઓગસ્ટ પગાર ન આપો — તે ૭ સપ્ટે છે.",
  "Hold farmer pay until the pad.": "પેડ ન થાય ત્યાં ખેડૂતના પૈસા રોકો.",
  "What to do": "શું કરવું",
  "Hide detail": "વિગત છુપાવો",
  "More detail": "વધુ વિગત",
  "Left village": "ગામ છોડ્યું",
  "Urja plant diary": "ઉર્જા પ્લાન્ટ ડાયરી",
  "Type here…": "અહીં લખો…",
  "How far this trip has gone. Then pay farmer, pay driver, or hold.":
    "આ ટ્રિપ કેટલી આગળ ગઈ. પછી ખેડૂતને પૈસા, ડ્રાઈવરને પૈસા, અથવા રોકો.",

  // tiers / pricing
  "Small factory": "નાની ફેક્ટરી",
  "Full plant": "પૂરો પ્લાન્ટ",
  "Carbon later": "કાર્બન પછી",
  "No tanks — only store, staff, bills": "ટાંકી નહીં — ફક્ત સ્ટોર, સ્ટાફ, બિલ",
  "The ₹75,000 plan — stop the holes": "₹૭૫,૦૦૦નો પ્લાન — છિદ્રો બંધ કરો",
  "Only when that money is real": "જ્યારે એ પૈસા સાચા હોય",
  "Any factory / godown": "કોઈ પણ ફેક્ટરી / ગોડાઉન",
  "CBG / biogas plant owners": "CBG / બાયોગેસ પ્લાન્ટ માલિક",
  "After the plant is tight": "પ્લાન્ટ કડક થયા પછી",
  "If you have no biogas tanks yet. Stock, who owes you, who you owe, staff.":
    "હજુ બાયોગેસ ટાંકી ન હોય. સ્ટોક, કોણ દેવું છે, તમે કોને દેવા, સ્ટાફ.",
  "One stopped day is ~₹49,500. One sour tank is ~₹10 lakh. This fee is smaller than those holes.":
    "એક બંધ દિવસ ~₹૪૯,૫૦૦. એક ખાટી ટાંકી ~₹૧૦ લાખ. આ ફી એ છિદ્રોથી નાની છે.",
  "Do not start here. Add this when carbon / govt papers can bring cash — not before.":
    "અહીંથી શરૂ ન કરો. કાર્બન / સરકારી કાગળ રોકડ લાવે ત્યારે ઉમેરો — પહેલા નહીં.",
  "Stock, buy orders, trucks in, wastage": "સ્ટોક, ખરીદી ઓર્ડર, ટ્રક અંદર, વેડફાટ",
  "What the floor is making + quality": "ફ્લોર શું બનાવે + ક્વોલિટી",
  "Bills, who is late, goods out": "બિલ, કોણ મોડું, માલ બહાર",
  "Pay suppliers + staff salary": "સપ્લાયર + સ્ટાફ પગાર આપો",
  "Only you tick big spends": "મોટા ખર્ચ પર ફક્ત તમે ટિક",
  "Everything in Small factory": "નાની ફેક્ટરીની બધી વાત",
  "Tank health — yellow before it dies": "ટાંકીની તબિયત — મરે તે પહેલા પીળું",
  "Which dung mix makes more gas ₹": "કયું ગોબર મિક્સ વધુ ગેસ ₹ આપે",
  "Pay farmer when weighbridge says OK": "વેબ્રિજ OK કહે ત્યારે ખેડૂતને પૈસા",
  "See gas wasted in the cleaner (₹ every day)": "ક્લીનરમાં વેડફાયેલો ગેસ જુઓ (રોજ ₹)",
  "Lab tests, dung mix, FOM bags, govt dates": "લેબ ટેસ્ટ, ગોબર મિક્સ, FOM બેગ, સરકારી તારીખ",
  "Everything in Full plant": "પૂરા પ્લાન્ટની બધી વાત",
  "Carbon money, step by step": "કાર્બન પૈસા, પગલે પગલે",
  "Papers the checker asks for": "ચેકર જે કાગળ માગે",
  "Fertilizer bag sales": "ખાતર બેગ વેચાણ",
  "Govt due dates on one page": "સરકારી તારીખ એક પેજ પર",
  "First-time plant setup": "પહેલી વાર પ્લાન્ટ સેટઅપ",
  "₹25,000 once": "₹૨૫,૦૦૦ એક વાર",
  "Your people, your items, your suppliers. Not every month.":
    "તમારા લોકો, તમારી વસ્તુ, તમારા સપ્લાયર. દર મહિને નહીં.",
  "Carbon papers (only if you take Carbon later)":
    "કાર્બન કાગળ (જો કાર્બન પછી લો તો)",
  "₹1–3 lakh once": "₹૧–૩ લાખ એક વાર",
  "Outside man asks ₹4–25 lakh for the same work.":
    "બહારનો માણસ એ જ કામ માટે ₹૪–૨૫ લાખ માગે.",
  "Tank sensors — only if you want them": "ટાંકી સેન્સર — જો તમે જોઈએ",
  "₹1.5–4 lakh / plant": "₹૧.૫–૪ લાખ / પ્લાન્ટ",
  "You can start with registers. No one forces machines on day one.":
    "રજિસ્ટરથી શરૂ કરી શકો. પહેલા દિવસે કોઈ મશીન ફરજિયાત નહીં.",
  "5–10% only on carbon money you actually get":
    "૫–૧૦% ફક્ત જે કાર્બન પૈસા ખરેખર મળે તેના પર",
  "Off unless you switch it on. We do not take a cut of your gas sales.":
    "તમે ચાલુ કરો ત્યાં સુધી બંધ. ગેસ વેચાણમાંથી કાપ નહીં.",
  "One number. No range.": "એક આંકડો. રેન્જ નહીં.",
  "+₹15,000 when you want papers": "કાગળ જોઈએ ત્યારે +₹૧૫,૦૦૦",
  "Extra — not in": "વધારાનું — આમાં નહીં",
  "You are on": "તમે છો",
  "This page is only if you take that box.": "આ પેજ ત્યારે જ જો તે બોક્સ લો.",
  "Tap a box to look. You do not pay to peek.": "જોવા બોક્સ ટેપ કરો. જોવા પૈસા નહીં.",
  "Back to Today": "આજે પર પાછા",
  "What extra costs": "વધારાનું શું ખર્ચ",

  // people bios / calls
  "Plant owner": "પ્લાન્ટ માલિક",
  "Office": "ઓફિસ",
  "I tick big spends. I want holes in rupees, not English essays.":
    "મોટા ખર્ચ પર હું ટિક કરું. રૂપિયામાં છિદ્રો જોઈએ, અંગ્રેજી નિબંધ નહીં.",
  "Your card": "તમારું કાર્ડ",
  "IOCL still holds ₹53,100 past due. Two spends wait for your tick. That is the hole — not a carbon essay.":
    "IOCL હજુ ₹૫૩,૧૦૦ બાકી રાખે છે. બે ખર્ચ તમારી ટિકની રાહ જુએ. આ છિદ્ર છે — કાર્બન નિબંધ નહીં.",
  "Call IOCL, or tick the Napier buy before the line stops.":
    "IOCLને ફોન કરો, અથવા લાઈન બંધ થાય તે પહેલા નેપિયર ખરીદી પર ટિક કરો.",
  "Late — IOCL": "મોડું — IOCL",
  "Still to collect": "હજુ વસૂલવાનું",
  "Open bills": "ખુલ્લા બિલ",
  "2 ticks": "૨ ટિક",
  "Napier PO + Anita advance": "નેપિયર PO + અનિતા એડવાન્સ",
  "Who owes": "કોણ દેવું",
  "Tick spends": "ખર્ચ પર ટિક",
  "Shift in-charge": "શિફ્ટ ઇન-ચાર્જ",
  "Tanks, mix, and the night crew. If D2 sours, it is on me.":
    "ટાંકી, મિક્સ, અને રાત્રિની ટીમ. D2 ખાટી થાય તો મારી જવાબદારી.",
  "Night shift + attend": "રાત્રિ શિફ્ટ + હાજરી",
  "Your shift": "તમારી શિફ્ટ",
  "You are in. D2 is the sick tank. One job on you can stop gas.":
    "તમે અંદર છો. D2 બીમાર ટાંકી છે. તમારું એક કામ ગેસ રોકી શકે.",
  "Open tanks, or finish the late job.": "ટાંકી ખોલો, અથવા મોડું કામ પૂરું કરો.",
  "Tanks on watch": "જોવાની ટાંકી",
  "D2 souring": "D2 ખાટી થાય છે",
  "Open jobs": "ખુલ્લા કામ",
  "One can stop the plant": "એક પ્લાન્ટ રોકી શકે",
  "Hours this week": "આ અઠવાડિયાના કલાક",
  "Night overlap": "રાત્રિ ઓવરલેપ",
  "My jobs": "મારા કામ",
  "Weighbridge / store": "વેબ્રિજ / સ્ટોર",
  "Purchase": "ખરીદી",
  "Lot numbers stay with the truck. No photo, no farmer pay.":
    "લોટ નંબર ટ્રક સાથે રહે. ફોટો નહીં તો ખેડૂતને પૈસા નહીં.",
  "Attend days": "હાજરીના દિવસ",
  "Store card": "સ્ટોર કાર્ડ",
  "You are in. Napier is short. One truck is on the pad waiting for a slip.":
    "તમે અંદર છો. નેપિયર ઓછું છે. એક ટ્રક પેડ પર સ્લિપની રાહ જુએ છે.",
  "Order grass, or weigh the pad truck.": "ઘાસ મંગાવો, અથવા પેડની ટ્રક તોળો.",
  "Trucks logged today": "આજે નોંધાયેલી ટ્રક",
  "One still on the road": "એક હજુ રસ્તે છે",
  "Napier left": "નેપિયર બાકી",
  "Line can stop": "લાઈન રોકાઈ શકે",
  "Advance still cut": "એડવાન્સ હજુ કપાય",
  "From July": "જુલાઈથી",
  "Order stock": "સ્ટોક મંગાવો",
  "Digester helper / floor": "ડાયજેસ્ટર હેલ્પર / ફ્લોર",
  "Feed, slurry, FOM bags. Late today — say why.":
    "ખોરાક, સ્લરી, FOM બેગ. આજે મોડા — કારણ કહો.",
  "Floor card": "ફ્લોર કાર્ડ",
  "You came at 07:40. Four late days this month already cut attend pay. FOM bags are still waiting.":
    "તમે ૦૭:૪૦એ આવ્યા. આ મહિને ચાર મોડા દિવસે હાજરી પગાર કપાયો. FOM બેગ હજુ રાહ જુએ છે.",
  "Start the bag job, or tell Suresh why you were late.":
    "બેગનું કામ શરૂ કરો, અથવા સુરેશને કહો કે શા માટે મોડા.",
  "Late this month": "આ મહિને મોડા",
  "Cuts attend pay": "હાજરી પગાર કાપે",
  "FOM bags waiting": "FOM બેગ રાહ જુએ",
  "Overdue job": "મોડું કામ",
  "Line now": "હવે લાઈન",
  "Upgrader A": "અપગ્રેડર A",
  "CBG running": "CBG ચાલે છે",
  "Purification · floor (not the truck driver)":
    "શુદ્ધિકરણ · ફ્લોર (ટ્રક ડ્રાઈવર નહીં)",
  "Scrubber and cylinders. I punch in and finish my jobs.":
    "સ્ક્રબર અને સિલિન્ડર. હું પંચ કરું અને કામ પૂરું કરું.",
  "Muster says you are absent today (16 Aug). Leave you asked is from 19 Aug — that is not today. If you are on site, HR must punch you in or this day is lost.":
    "મસ્ટર કહે આજે (૧૬ ઓગસ્ટ) ગેરહાજર. માગેલી રજા ૧૯ ઓગસ્ટથી — આજે નહીં. સાઈટ પર હો તો HRએ પંચ કરવું પડે નહીં તો દિવસ જતો રહે.",
  "Ask HR to punch you in, or sit the leave you already asked.":
    "HRને પંચ કરાવો, અથવા માગેલી રજા બેસો.",
  "Marked today": "આજે માર્ક",
  "Ask HR if you are on site": "સાઈટ પર હો તો HRને કહો",
  "Leave asked": "રજા માગી",
  "From 19 Aug": "૧૯ ઓગસ્ટથી",
  "Last take-home": "છેલ્લું હાથ પર",
  "July, paid 7 Aug": "જુલાઈ, ૭ ઓગસ્ટે ચૂકવ્યું",
  "Lab sample": "લેબ સેમ્પલ",
  "Quality": "ક્વોલિટી",
  "Morning VFA and alkalinity. D2 is my first draw.":
    "સવારની VFA અને આલ્કલિનિટી. D2 મારો પહેલો નમૂનો.",
  "Lab card": "લેબ કાર્ડ",
  "D2 acids are high. That matches the souring warning. You are the one who proves it.":
    "D2 એસિડ ઊંચા છે. સાવરિંગની ચેતવણી સાથે મળે. સાબિતી તમારી.",
  "Log the next sample, or tell Suresh to slow feed.":
    "આગલી સેમ્પલ લખો, અથવા સુરેશને ખોરાક ધીમો કરવાનું કહો.",
  "Samples today": "આજની સેમ્પલ",
  "D2 VFA high": "D2 VFA ઊંચું",
  "Days present": "હાજર દિવસ",
  "Best on the floor": "ફ્લોર પર સૌથી સારું",
  "Next draw": "આગલો નમૂનો",
  "Tomorrow 06:00": "કાલે ૦૬:૦૦",
  "Same tank": "એ જ ટાંકી",
  "Dung collection driver": "ગોબર કલેક્શન ડ્રાઈવર",
  "Collection": "કલેક્શન",
  "Village pit to weighbridge. License MH15 2019 004812.":
    "ગામના ખાડાથી વેબ્રિજ. લાઈસન્સ MH15 2019 004812.",
  "Trip extra (tonnes)": "ટ્રિપ વધારો (ટન)",
  "Driver pay": "ડ્રાઈવર પગાર",
  "July salary already left on 7 Aug. August monthly ₹19,000 pays 7 Sep. Trip extra this month ₹8,400 — today’s dung is still on the road, so this trip is not in extras yet.":
    "જુલાઈ પગાર ૭ ઓગસ્ટે નીકળી ગયો. ઓગસ્ટ મહિનાનું ₹૧૯,૦૦૦ ૭ સપ્ટેએ. આ મહિને ટ્રિપ વધારો ₹૮,૪૦૦ — આજનું ગોબર હજુ રસ્તે છે, તેથી આ ટ્રિપ વધારામાં નથી.",
  "Finish this trip. Do not ask Accounts for August pay today.":
    "આ ટ્રિપ પૂરી કરો. આજે એકાઉન્ટ્સને ઓગસ્ટ પગાર ન માગો.",
  "Working days": "કામના દિવસ",
  "1 absent this month": "આ મહિને ૧ ગેરહાજર",
  "Trips this month": "આ મહિનાની ટ્રિપ",
  "Today still on the road": "આજે હજુ રસ્તે",
  "Tonnes hauled": "ટન લાવ્યા",
  "Trip extra from this": "આમાંથી ટ્રિપ વધારો",
  "KM this month": "આ મહિનાના કિમી",
  "Plant diesel": "પ્લાન્ટ ડીઝલ",
  "Hours today": "આજના કલાક",
  "Left Wavi 05:40": "વાવી ૦૫:૪૦એ છોડ્યું",
  "This trip extra": "આ ટ્રિપનો વધારો",
  "Waits": "રાહ",
  "Weighbridge first": "પહેલા વેબ્રિજ",
  "My truck": "મારી ટ્રક",
  "Hold — wait for pad": "રોકો — પેડની રાહ",
  "Napier collection driver": "નેપિયર કલેક્શન ડ્રાઈવર",
  "Napier belt. License MH12 2021 009104.": "નેપિયર બેલ્ટ. લાઈસન્સ MH12 2021 009104.",
  "Trip extra (today pad OK)": "ટ્રિપ વધારો (આજે પેડ OK)",
  "You are on the pad. This trip can count. Monthly ₹18,500 plus extras ₹7,260 this month so far. August monthly still pays 7 Sep.":
    "તમે પેડ પર છો. આ ટ્રિપ ગણાય. મહિનાનું ₹૧૮,૫૦૦ વત્તા અત્યાર સુધી વધારો ₹૭,૨૬૦. ઓગસ્ટ મહિનાનું હજુ ૭ સપ્ટેએ.",
  "Count this trip in extras. Do not ask for August salary today.":
    "આ ટ્રિપ વધારામાં ગણો. આજે ઓગસ્ટ પગાર ન માગો.",
  "2 absent": "૨ ગેરહાજર",
  "On the pad now": "હવે પેડ પર",
  "Short belt": "ટૂંકી બેલ્ટ",
  "At weighbridge": "વેબ્રિજ પર",
  "Today’s trip extra": "આજની ટ્રિપનો વધારો",
  "Weight OK — can count": "વજન OK — ગણાય",
  "Pay day is 7 Sep": "પગાર ૭ સપ્ટેએ",
  "Residue truck driver — not floor Kiran Jadhav":
    "અવશેષ ટ્રક ડ્રાઈવર — ફ્લોર કિરણ જાધવ નહીં",
  "Residue coop loop. License MH16 2018 002271.":
    "અવશેષ કો-ઓપ લૂપ. લાઈસન્સ MH16 2018 002271.",
  "Trip extra so far": "અત્યાર સુધી ટ્રિપ વધારો",
  "Still loading. This trip does not count. Advance ₹1,500 comes off the 7 Sep pay, not today.":
    "હજુ લોડ થાય છે. આ ટ્રિપ ગણાય નહીં. એડવાન્સ ₹૧,૫૦૦ ૭ સપ્ટેના પગારમાંથી કપાય, આજે નહીં.",
  "Finish loading and photo the pit, or hold — extras wait.":
    "લોડ પૂરું કરો અને ખાડાનો ફોટો, અથવા રોકો — વધારો રાહ જુએ.",
  "Advance ₹1,500 still cutting": "એડવાન્સ ₹૧,૫૦૦ હજુ કપાય છે",
  "Still loading": "હજુ લોડ થાય છે",
  "Residue": "અવશેષ",
  "Longer loop": "લાંબી લૂપ",
  "Not left the coop": "કો-ઓપ છોડ્યું નથી",
  "Not yet": "હજુ નહીં",
  "No photo, no weight": "ફોટો નહીં, વજન નહીં",
  "Hold extras": "વધારો રોકો",
  "IOCL, CGD, local cylinders. Collect before you chase new orders.":
    "IOCL, CGD, સ્થાનિક સિલિન્ડર. નવા ઓર્ડર પહેલા વસૂલો.",
  "Collection incentive": "વસૂલી ઇન્સેન્ટિવ",
  "Sales card": "વેચાણ કાર્ડ",
  "IOCL is late by ₹53,100. Coop FOM ₹70,000 is blocked on credit. Incentive waits on the late call.":
    "IOCL ₹૫૩,૧૦૦ મોડું. કો-ઓપ FOM ₹૭૦,૦૦૦ ક્રેડિટ પર બ્લોક. ઇન્સેન્ટિવ મોડા કોલની રાહ જુએ.",
  "Call the late buyer, or hold their next truck.":
    "મોડા ખરીદનારને ફોન કરો, અથવા તેમની આગલી ટ્રક રોકો.",
  "Late to collect": "વસૂલવામાં મોડું",
  "Still open": "હજુ ખુલ્લું",
  "All unpaid bills": "બધા બાકી બિલ",
  "Blocked credit": "બ્લોક ક્રેડિટ",
  "Coop FOM — do not load": "કો-ઓપ FOM — લોડ ન કરો",
  "Accounts": "એકાઉન્ટ્સ",
  "In, out, ticks. August salary run is 7 Sep.":
    "અંદર, બહાર, ટિક. ઓગસ્ટ પગાર ૭ સપ્ટેએ.",
  "Accounts card": "એકાઉન્ટ્સ કાર્ડ",
  "Two spends wait on the owner. Driver August pay is 7 Sep — do not pay it today. You tick what the desk typed.":
    "બે ખર્ચ માલિકની રાહ જુએ. ડ્રાઈવર ઓગસ્ટ પગાર ૭ સપ્ટે — આજે ન આપો. ડેસ્કે લખ્યું તેના પર તમે ટિક.",
  "Open Cash, or pay the top supplier.": "રોકડ ખોલો, અથવા ટોચના સપ્લાયરને પૈસા આપો.",
  "Ticks waiting": "ટિકની રાહ",
  "Owner must say yes": "માલિકે હા કહેવી પડે",
  "Salary run": "પગાર ચાલે",
  "26 people": "૨૬ લોકો",
  "We still owe": "અમારું હજુ દેવું",
  "Suppliers": "સપ્લાયર",
  "Pay so trucks come": "પૈસા આપો કે ટ્રક આવે",
  "Pay out": "પૈસા આપો",
  "Muster, leave, hire. A person exists when I type them on Staff.":
    "મસ્ટર, રજા, નવી ભરતી. સ્ટાફ પર લખું ત્યારે વ્યક્તિ અસ્તિત્વમાં આવે.",
  "HR card": "HR કાર્ડ",
  "Purification is uncovered. One leave is waiting. Every person has a card — open it, do not dump a list.":
    "શુદ્ધિકરણ ખાલી છે. એક રજા રાહ જુએ. દરેક વ્યક્તિનું કાર્ડ છે — ખોલો, યાદી ન ફેંકો.",
  "Move someone, or open a person’s card.": "કોઈને ખસેડો, અથવા વ્યક્તિનું કાર્ડ ખોલો.",
  "Outside checker": "બહારનો ચેકર",
  "Look at proof. Cannot change a line. Cannot see staff pay.":
    "પુરાવો જુઓ. લાઈન બદલી શકાય નહીં. સ્ટાફ પગાર ન જોઈ શકાય.",
  "Auditor card": "ચેકર કાર્ડ",
  "You are not on this plant’s payroll. Open proof. Flag a gap. You cannot edit.":
    "તમે આ પ્લાન્ટના પગાર પર નથી. પુરાવો ખોલો. ગેપ ફ્લેગ કરો. ફેરફાર નહીં.",
  "Open the locker, or the monitoring pack.": "લોકર ખોલો, અથવા મોનિટરિંગ પેક.",
  "Urja platform": "ઉર્જા પ્લેટફોર્મ",
  "All client plants. Not on Greenfield salary.":
    "બધા ક્લાયન્ટ પ્લાન્ટ. ગ્રીનફીલ્ડ પગાર પર નહીં.",
  "Platform": "પ્લેટફોર્મ",
  "This seat is Urja, not a plant worker. Switch plant from the left.":
    "આ સીટ ઉર્જાની છે, પ્લાન્ટ કામદારની નહીં. ડાબેથી પ્લાન્ટ બદલો.",
  "Open Nashik as the owner would.": "માલિકની જેમ નાશિક ખોલો.",
  "New on the book": "નોંધમાં નવું",
  "Days and pay will show after the first month.":
    "પહેલા મહિના પછી દિવસ અને પગાર દેખાશે.",
  "Open Staff to edit, or leave the card as it is.":
    "ફેરફાર માટે સ્ટાફ ખોલો, અથવા કાર્ડ જેમ છે તેમ રાખો.",
  "was typed by": "ને લખ્યા",

  // search
  "IOCL overdue ₹53,100": "IOCL બાકી ₹૫૩,૧૦૦",
  "Napier grass — 1.5 days left": "નેપિયર ઘાસ — ૧.૫ દિવસ બાકી",
  "PO-442 waiting owner tick": "PO-442 માલિકની ટિકની રાહ",
  "Your yes": "તમારી હા",
  "Truck MH-15 on the way": "ટ્રક MH-15 રસ્તે છે",
  "Digester 2 souring": "ડાયજેસ્ટર ૨ ખાટી થાય છે",
  "Kiran Jadhav absent (floor, not truck)": "કિરણ જાધવ ગેરહાજર (ફ્લોર, ટ્રક નહીં)",
  "Kiran Pawar residue truck MH 16 KP 3304": "કિરણ પવાર અવશેષ ટ્રક MH 16 KP 3304",
  "Meena Pawar — D2 VFA high": "મીના પવાર — D2 VFA ઊંચું",
  "Talk to Suresh": "સુરેશ સાથે વાત",
  "GST check 31 Aug": "GST ચેક ૩૧ ઓગસ્ટ",
  "Govt date": "સરકારી તારીખ",
  "Fire NOC": "ફાયર NOC",
  "Pay Ganesh Transport": "ગણેશ ટ્રાન્સપોર્ટને પૈસા",

  // common page chrome
  "Actions": "કામ",
  "Amount": "રકમ",
  "Amount ₹": "રકમ ₹",
  "Approved — send": "મંજૂર — મોકલો",
  "Area": "વિસ્તાર",
  "Balance": "બાકી",
  "Batch": "બેચ",
  "Bags": "બેગ",
  "Bags in stock": "સ્ટોકમાં બેગ",
  "Buyer": "ખરીદનાર",
  "Call": "કોલ",
  "Came late": "મોડા આવ્યા",
  "Can improve": "સુધારી શકાય",
  "Can stop the plant": "પ્લાન્ટ રોકી શકે",
  "Carbon money": "કાર્બન પૈસા",
  "Change plan": "પ્લાન બદલો",
  "Change the mix": "મિક્સ બદલો",
  "Clear": "સાફ",
  "Collect": "વસૂલો",
  "Collect first": "પહેલા વસૂલો",
  "Collect this — it is yours": "આ વસૂલો — આ તમારું છે",
  "Contact": "સંપર્ક",
  "Coverage": "કવરેજ",
  "Credit stop": "ક્રેડિટ સ્ટોપ",
  "Credits ready": "ક્રેડિટ તૈયાર",
  "Customer": "ગ્રાહક",
  "Cycle": "ચક્ર",
  "Cylinders filled": "સિલિન્ડર ભર્યા",
  "Desk / dept": "ડેસ્ક / વિભાગ",
  "Device ID": "ડિવાઈસ ID",
  "Do this first": "આ પહેલા કરો",
  "Done": "પૂરું",
  "Done — stock updated": "પૂરું — સ્ટોક અપડેટ",
  "Draft": "ડ્રાફ્ટ",
  "Driver (can take a truck)": "ડ્રાઈવર (ટ્રક લઈ શકે)",
  "Driver (from Staff)": "ડ્રાઈવર (સ્ટાફમાંથી)",
  "Drop photo or PDF here": "ફોટો અથવા PDF અહીં મૂકો",
  "Due": "તારીખ",
  "East belt · Dindori": "પૂર્વ બેલ્ટ · દિંડોરી",
  "Email reminders": "ઈમેઈલ યાદ",
  "Farmer": "ખેડૂત",
  "Farmers still waiting": "ખેડૂતો હજુ રાહ જુએ",
  "Feed change": "ખોરાક બદલો",
  "File started": "ફાઈલ શરૂ",
  "Fill oldest gap": "જૂનો ગેપ ભરો",
  "Fix first": "પહેલા સુધારો",
  "Floor": "ફ્લોર",
  "Floor call": "ફ્લોરનો નિર્ણય",
  "Floor is clear": "ફ્લોર સાફ છે",
  "FOM sales this month": "આ મહિને FOM વેચાણ",
  "Full house": "ભરેલું ઘર",
  "Gap": "ગેપ",
  "Gaps": "ગેપ",
  "Gas made → clean CBG sold": "ગેસ બન્યો → સાફ CBG વેચાયો",
  "Give to": "આપો",
  "Godown": "ગોડાઉન",
  "Grade": "ગ્રેડ",
  "Grade A": "ગ્રેડ A",
  "Grade B": "ગ્રેડ B",
  "HR": "HR",
  "Handled": "થયું",
  "Health over days": "દિવસોની તબિયત",
  "Hold extra feed": "વધારાનો ખોરાક રોકો",
  "Hold next truck": "આગલી ટ્રક રોકો",
  "Hold the line": "લાઈન રોકો",
  "Hold this lot": "આ લોટ રોકો",
  "In vs Out": "અંદર-બહાર",
  "Invite email": "ઈમેઈલ મોકલો",
  "Item": "વસ્તુ",
  "Job": "કામ",
  "Just now on the floor": "હમણાં ફ્લોર પર",
  "Keep running": "ચાલુ રાખો",
  "Kind": "પ્રકાર",
  "Last change": "છેલ્લો ફેરફાર",
  "Late money": "મોડા પૈસા",
  "Later": "પછી",
  "Leave calendar": "રજાનું કેલેન્ડર",
  "Leave score": "રજા સ્કોર",
  "Leave waiting": "રજા રાહ જુએ",
  "Left the gate": "ગેટથી નીકળ્યું",
  "License": "લાઈસન્સ",
  "Line": "લાઈન",
  "Line uncovered": "લાઈન ખાલી",
  "Liquid": "પ્રવાહી",
  "Load": "લોડ",
  "Location (map pin)": "સ્થળ (નકશાની પિન)",
  "Log FOM bags": "FOM બેગ લખો",
  "Log new FOM batch": "નવી FOM બેચ લખો",
  "Log new truck": "નવી ટ્રક લખો",
  "Looking good": "સારું લાગે",
  "Looks fine": "ઠીક લાગે",
  "Lot": "લોટ",
  "Maps": "નકશા",
  "Missing": "ખૂટે",
  "Missing data?": "ડેટા ખૂટે?",
  "Mixed waste heavy": "મિક્સ કચરો વધુ",
  "Money on the floor": "ફ્લોર પર પૈસા",
  "Money sitting outside": "બહાર પડેલા પૈસા",
  "Name": "નામ",
  "Needs a person": "વ્યક્તિ જોઈએ",
  "Needs owner": "માલિક જોઈએ",
  "Needs your yes": "તમારી હા જોઈએ",
  "New job": "નવું કામ",
  "New order": "નવો ઓર્ડર",
  "New orders": "નવા ઓર્ડર",
  "No card": "કાર્ડ નથી",
  "No card on this login yet.": "આ લોગિન પર હજુ કાર્ડ નથી.",
  "No drafts": "ડ્રાફ્ટ નથી",
  "No plant-stop jobs": "પ્લાન્ટ રોકે તેવા કામ નથી",
  "Nobody late": "કોઈ મોડું નહીં",
  "None late": "કોઈ મોડું નહીં",
  "None yet": "હજુ કંઈ નહીં",
  "North belt · Wavi–Nandur": "ઉત્તર બેલ્ટ · વાવી–નંદુર",
  "Not billed yet": "હજુ બિલ નથી",
  "Not your card": "તમારું કાર્ડ નહીં",
  "Nothing finished yet": "હજુ કંઈ પૂરું નથી",
  "Nothing late": "કંઈ મોડું નહીં",
  "Nothing on line": "લાઈન પર કંઈ નહીં",
  "Nothing waiting": "કંઈ રાહ નથી",
  "Number of tanks": "ટાંકીની સંખ્યા",
  "Number plate": "નંબર પ્લેટ",
  "On now": "હવે ચાલે",
  "On the floor": "ફ્લોર પર",
  "On the line": "લાઈન પર",
  "Open": "ખોલો",
  "Open card": "કાર્ડ ખોલો",
  "Open latest": "નવું ખોલો",
  "Open newest pack": "નવો પેક ખોલો",
  "Open proof": "પુરાવો ખોલો",
  "Open proof locker": "પુરાવા લોકર ખોલો",
  "Open tanks": "ટાંકી ખોલો",
  "Order": "ઓર્ડર",
  "Overdue": "મોડું",
  "Owner tick": "માલિકની ટિક",
  "Paid": "ચૂકવ્યું",
  "Paid?": "ચૂકવ્યું?",
  "Paper": "કાગળ",
  "Paper cupboard": "કાગળની અલમારી",
  "Past due date": "તારીખ નીકળી",
  "Path": "પાથ",
  "Pay so trucks keep coming": "પૈસા આપો કે ટ્રક આવતી રહે",
  "Pay this week": "આ અઠવાડિયે પૈસા આપો",
  "Phone": "ફોન",
  "Photo the probe": "પ્રોબનો ફોટો",
  "Pipeline injection": "પાઈપલાઈન ઇન્જેક્શન",
  "Plant at dusk": "સાંજે પ્લાન્ટ",
  "Plant at risk": "પ્લાન્ટ જોખમમાં",
  "Plant name": "પ્લાન્ટનું નામ",
  "Plant staff": "પ્લાન્ટ સ્ટાફ",
  "Plant story paper": "પ્લાન્ટની વાતનો કાગળ",
  "Post": "પોસ્ટ",
  "Price lever": "કિંમતનો લીવર",
  "Priority": "પ્રાથમિકતા",
  "Prod": "ઉત્પાદન",
  "Product": "પ્રોડક્ટ",
  "Proof locker": "પુરાવા લોકર",
  "Qty": "જથ્થો",
  "Raw": "કાચું",
  "Read only": "ફક્ત વાંચો",
  "Remind me": "યાદ કરાવો",
  "Renew first": "પહેલા રિન્યુ",
  "Running": "ચાલે છે",
  "Sale": "વેચાણ",
  "Sales in": "વેચાણ અંદર",
  "Save batch": "બેચ સેવ",
  "Save job": "કામ સેવ",
  "Save order": "ઓર્ડર સેવ",
  "Save payment": "પેમેન્ટ સેવ",
  "Save person": "વ્યક્તિ સેવ",
  "Save purchase": "ખરીદી સેવ",
  "Save truck": "ટ્રક સેવ",
  "Second cash": "બીજી રોકડ",
  "See": "જુઓ",
  "See the warning": "ચેતવણી જુઓ",
  "Self": "પોતે",
  "Send lab": "લેબ મોકલો",
  "Sent for check": "ચેક માટે મોકલ્યું",
  "Shift note — bold / list": "શિફ્ટ નોંધ — બોલ્ડ / યાદી",
  "Size (TPD)": "સાઈઝ (TPD)",
  "Solid": "ઘન",
  "South coop loop": "દક્ષિણ કો-ઓપ લૂપ",
  "Speed": "ઝડપ",
  "Spend dates": "ખર્ચની તારીખ",
  "Spend out": "ખર્ચ બહાર",
  "Stable but not peak": "સ્થિર પણ ટોચ નહીં",
  "Start a floor job — Production types this":
    "ફ્લોર કામ શરૂ — ઉત્પાદન આ લખે",
  "Status": "સ્થિતિ",
  "Stay or change": "રાખો અથવા બદલો",
  "Step": "પગલું",
  "Still counting": "હજુ ગણાય છે",
  "Stop — quality fail": "રોકો — ક્વોલિટી નાપાસ",
  "Stop the plant": "પ્લાન્ટ રોકો",
  "Store": "સ્ટોર",
  "Store, salary, power": "સ્ટોર, પગાર, પાવર",
  "Streams working?": "સ્ટ્રીમ ચાલે?",
  "Supplier": "સપ્લાયર",
  "Talk on the job": "કામ પર વાત",
  "Tank": "ટાંકી",
  "Tank call": "ટાંકીનો નિર્ણય",
  "Tank health — stop a crash early": "ટાંકીની તબિયત — ક્રેશ વહેલો રોકો",
  "Team & bill": "ટીમ અને બિલ",
  "Tell store": "સ્ટોરને કહો",
  "Things to fix": "સુધારવાનું",
  "This week": "આ અઠવાડિયે",
  "Tick": "ટિક",
  "Today’s call": "આજનો નિર્ણય",
  "Truck dispatch": "ટ્રક રવાના",
  "Truck short": "ટ્રક ઓછી",
  "Type": "પ્રકાર",
  "Version": "વર્ઝન",
  "Village / pit": "ગામ / ખાડો",
  "Wait": "રાહ",
  "Waiting": "રાહ",
  "Waiting for owner": "માલિકની રાહ",
  "Waiting photo proof": "ફોટો પુરાવાની રાહ",
  "Waiting to start": "શરૂ થવાની રાહ",
  "Watch this": "આ જુઓ",
  "Weak site": "નબળી સાઈટ",
  "Weight": "વજન",
  "What you feed in": "શું નાખો છો",
  "When": "ક્યારે",
  "When free": "જ્યારે ખાલી",
  "When money is due": "પૈસાની તારીખ",
  "Where it went": "ક્યાં ગયું",
  "Where the paper sits": "કાગળ ક્યાં છે",
  "Which truck": "કઈ ટ્રક",
  "Who changed what": "કોણે શું બદલ્યું",
  "Who is off this month": "આ મહિને કોણ છુટ્ટી પર",
  "Who to pay": "કોને પૈસા આપવા",
  "Will run out": "ખૂટી જશે",
  "Will the line stop?": "લાઈન રોકાશે?",
  "With Urja": "ઉર્જા સાથે",
  "Without plant vs with plant": "પ્લાન્ટ વગર વિ પ્લાન્ટ સાથે",
  "Write a buy": "ખરીદી લખો",
  "Write a remark…": "નોંધ લખો…",
  "Yield": "ઉપજ",
  "You can only open your own card.": "તમે ફક્ત તમારું કાર્ડ ખોલી શકો.",
  "Your bill": "તમારું બિલ",
  "Your plan": "તમારો પ્લાન",
  "Your seat": "તમારી સીટ",
  "One call for today. The rest can wait.": "આજે એક નિર્ણય. બાકી રાહ જોઈ શકે.",
  "Machines working?": "મશીન ચાલે?",
  "Add staff": "સ્ટાફ ઉમેરો",
  "Add GST paper": "GST કાગળ ઉમેરો",
  "Advance waiting": "એડવાન્સ રાહ જુએ",
  "Against (GRN / lot)": "સામે (GRN / લોટ)",
  "All my plants": "મારા બધા પ્લાન્ટ",
  "All quiet": "બધું શાંત",
  "Assign a job — pick who from Staff": "કામ આપો — સ્ટાફમાંથી કોણ પસંદ કરો",
  "Auditor": "ચેકર",
  "Auditor checking": "ચેકર ચેક કરે છે",
  "Auditor papers": "ચેકરના કાગળ",
  "Auditor view": "ચેકરનું જોવું",
  "Auto-paid to UPI": "UPI પર ઓટો-પે",
  "Avoid if possible": "શક્ય હોય તો ટાળો",
  "Back to my desk": "મારી ડેસ્ક પર પાછા",
  "Best gas": "સૌથી સારો ગેસ",
  "Best mix": "સૌથી સારું મિક્સ",
  "Best this quarter": "આ ત્રિમાસમાં સૌથી સારું",
  "Better price score": "સારો ભાવ સ્કોર",
  "Billed to customers": "ગ્રાહકોને બિલ",
  "Buyer payment pending": "ખરીદનારની ચુકવણી બાકી",
  "Change log": "ફેરફારની નોંધ",
  "Chase unpaid FOM": "બાકી FOM વસૂલો",
  "Clean CBG": "સાફ CBG",
  "Do not add residue": "અવશેષ ન નાખો",
  "Do soon": "જલ્દી કરો",
  "Drop GST, NOC, photos of trucks. So nothing lives only on WhatsApp.":
    "GST, NOC, ટ્રકના ફોટો મૂકો. કંઈ ફક્ત વોટ્સએપ પર ન રહે.",
  "Drop that paper now, or wait until the date is red.":
    "એ કાગળ હવે મૂકો, અથવા તારીખ લાલ થાય ત્યાં રાહ.",
  "Every hire, truck, job, buy, sale and pay — with the person who typed it.":
    "દરેક ભરતી, ટ્રક, કામ, ખરીદી, વેચાણ અને પે — જેણે લખ્યું તેની સાથે.",
  "Every person on this plant has a card. Open one — days, pay, and what that job must do.":
    "આ પ્લાન્ટના દરેક વ્યક્તિનું કાર્ડ છે. એક ખોલો — દિવસ, પગાર, અને એ કામે શું કરવું.",
  "Every photo, weight, and gas sale is locked here. Nobody can change it after writing.":
    "દરેક ફોટો, વજન અને ગેસ વેચાણ અહીં લોક. લખ્યા પછી કોઈ બદલી શકે નહીં.",
  "Fill the oldest gap now, or wait and risk the paper.":
    "જૂનો ગેપ હવે ભરો, અથવા રાહ જુઓ અને કાગળ જોખમમાં.",
  "Filter machine scorecard": "ફિલ્ટર મશીન સ્કોરકાર્ડ",
  "Find gaps before the auditor does — missing hours or bad tickets can stop your carbon money.":
    "ચેકર પહેલા ગેપ શોધો — ખૂટતા કલાક કે ખરાબ ટિકિટ કાર્બન પૈસા રોકે.",
  "Fix the filter if this keeps happening, or accept the leak for today.":
    "આ ચાલુ રહે તો ફિલ્ટર સુધારો, અથવા આજે લીક સ્વીકારો.",
  "Green = working. Yellow = weak. Red = silent. Fix silent ones first.":
    "લીલું = ચાલે. પીળું = નબળું. લાલ = શાંત. પહેલા શાંત સુધારો.",
  "Hire someone — they must exist here before Trucks can assign a driver":
    "કોઈને રાખો — ટ્રક ડ્રાઈવર આપે તે પહેલા તેઓ અહીં હોવા જોઈએ",
  "Hospital monitor for each digester": "દરેક ડાયજેસ્ટર માટે હોસ્પિટલ મોનિટર",
  "Hover the gold days. Floor Kiran Jadhav is on leave — not truck driver Kiran Pawar.":
    "સોનેરી દિવસ પર હોવર. ફ્લોર કિરણ જાધવ રજા પર — ટ્રક ડ્રાઈવર કિરણ પવાર નહીં.",
  "How much climate benefit you captured, what it is worth in ₹, and where it sits in the credit journey.":
    "કેટલો આબોહવા ફાયદો પકડ્યો, ₹માં કિંમત, અને ક્રેડિટ યાત્રામાં ક્યાં છે.",
  "If a number is on a screen, this list shows who put it there.":
    "સ્ક્રીન પર આંકડો હોય તો આ યાદી કહે કોણે મૂક્યો.",
  "If photos, weights, or sensors are missing, fix it here first.":
    "ફોટો, વજન કે સેન્સર ખૂટે તો પહેલા અહીં સુધારો.",
  "If you own more than one plant, start here. Spot the weak site fast.":
    "એકથી વધુ પ્લાન્ટ હોય તો અહીંથી શરૂ. નબળી સાઈટ જલ્દી જુઓ.",
  "Keep Full plant if the holes are bigger than the fee. Do not buy carbon papers until T2 is earning.":
    "છિદ્રો ફી કરતાં મોટા હોય તો પૂરો પ્લાન્ટ રાખો. T2 કમાય ત્યાં સુધી કાર્બન કાગળ ન ખરીદો.",
  "Keep running, or send lab if you do not trust the number.":
    "ચાલુ રાખો, અથવા આંકડા પર વિશ્વાસ ન હોય તો લેબ મોકલો.",
  "Leave and shift holes sit here — not on a separate Dates page.":
    "રજા અને શિફ્ટના છિદ્રો અહીં — અલગ તારીખ પેજ પર નહીં.",
  "Like a shop balance: what went in should match what came out (within a small gap).":
    "દુકાનના બેલેન્સ જેવું: અંદર ગયું તે બહાર આવ્યા સાથે મળે (નાના ગેપમાં).",
  "Live pH, heat, and gas (CH₄ / CO₂ / H₂S) for each tank. Catch souring before weeks of gas are lost.":
    "દરેક ટાંકી માટે લાઈવ pH, ગરમી અને ગેસ (CH₄ / CO₂ / H₂S). અઠવાડિયાનો ગેસ જાય તે પહેલા સાવરિંગ પકડો.",
  "Lock today’s photos": "આજના ફોટો લોક કરો",
  "Log truck — pick a driver from Staff": "ટ્રક લખો — સ્ટાફમાંથી ડ્રાઈવર પસંદ કરો",
  "Make auditor paper": "ચેકરનો કાગળ બનાવો",
  "Money in hand": "હાથમાં પૈસા",
  "New order — Sales types this. It does not appear by itself.":
    "નવો ઓર્ડર — વેચાણ આ લખે. પોતે ન આવે.",
  "Office desk for people and money": "લોકો અને પૈસા માટે ઓફિસ ડેસ્ક",
  "OK (under 3%)": "OK (૩%થી ઓછું)",
  "OK when dung short": "ગોબર ઓછું હોય ત્યારે OK",
  "Old way": "જૂની રીત",
  "On the change log": "ફેરફારની નોંધમાં",
  "One click makes the papers auditors need — avoid a big consultant bill.":
    "એક ક્લિકે ચેકરને જોઈતા કાગળ — મોટું કન્સલ્ટન્ટ બિલ ટાળો.",
  "One number for the full plant. If the holes on your ground are smaller than this, do not pay.":
    "પૂરા પ્લાન્ટ માટે એક આંકડો. જમીન પરના છિદ્રો આનાથી નાના હોય તો પૈસા ન આપો.",
  "One sick tank can stop gas for weeks. This page is your early warning.":
    "એક બીમાર ટાંકી અઠવાડિયા સુધી ગેસ રોકે. આ પેજ વહેલી ચેતવણી છે.",
  "Only you add staff. Open What it costs if you want to see ₹20,000 vs ₹75,000 vs ₹90,000. Table below = who can open what.":
    "ફક્ત તમે સ્ટાફ ઉમેરો. ₹૨૦,૦૦૦ વિ ₹૭૫,૦૦૦ વિ ₹૯૦,૦૦૦ જોવા ખર્ચ ખોલો. નીચે ટેબલ = કોણ શું ખોલે.",
  "Open a finished trip below. Pay this load, or pay the driver monthly.":
    "નીચે પૂરી ટ્રિપ ખોલો. આ લોડના પૈસા, અથવા ડ્રાઈવરને મહિનાના પૈસા.",
  "Open that plant now, or keep looking at Nashik.":
    "એ પ્લાન્ટ હવે ખોલો, અથવા નાશિક જોતા રહો.",
  "Open the desk that wrote it if something looks wrong.":
    "કંઈ ખોટું લાગે તો જે ડેસ્કે લખ્યું તે ખોલો.",
  "PO ticks and pay-outs sit on Cash — Excel/PDF stay on this page too.":
    "PO ટિક અને પે-આઉટ રોકડ પર — Excel/PDF પણ આ પેજ પર.",
  "Pay a supplier — Accountant types this slip":
    "સપ્લાયરને પૈસા — એકાઉન્ટન્ટ આ સ્લિપ લખે",
  "Pay this name now, or hold if the weighbridge is still short.":
    "આ નામને હવે પૈસા આપો, અથવા વેબ્રિજ હજુ ઓછું હોય તો રોકો.",
  "Push the auditor pack, or wait — this money does not pay today’s diesel.":
    "ચેકર પેક ધકેલો, અથવા રાહ — આ પૈસા આજના ડીઝલ ન ભરે.",
  "Raw biogas in, clean CBG out. See purification efficiency (CH₄ kept) and where gas went — cylinders, truck, or pipe.":
    "કાચો બાયોગેસ અંદર, સાફ CBG બહાર. શુદ્ધિકરણ કાર્યક્ષમતા (CH₄ રાખ્યું) અને ગેસ ક્યાં ગયો — સિલિન્ડર, ટ્રક, કે પાઈપ.",
  "Send a fitter to the silent meter, or wait till morning.":
    "શાંત મીટર પર ફિટર મોકલો, અથવા સવાર સુધી રાહ.",
  "Send a person to D2": "D2 પર વ્યક્તિ મોકલો",
  "Send fitter (job)": "ફિટર મોકલો (કામ)",
  "Sensors and meters must be online. If one goes dark, your numbers — and money — get weak.":
    "સેન્સર અને મીટર ઓનલાઈન હોવા જોઈએ. એક અંધારું થાય તો આંકડા — અને પૈસા — નબળા પડે.",
  "Slow the feed on the sick tank, send a lab sample, or wait and watch.":
    "બીમાર ટાંકી પર ખોરાક ધીમો, લેબ સેમ્પલ મોકલો, અથવા રાહ જોઈને જુઓ.",
  "Slurry → fertilizer money (FOM)": "સ્લરી → ખાતરના પૈસા (FOM)",
  "Smart warnings coming later": "સ્માર્ટ ચેતવણી પછી આવશે",
  "Soon this box will tell you if a tank is going bad before you lose gas.":
    "ટાંકી ખરાબ થાય અને ગેસ જાય તે પહેલા આ બોક્સ કહેશે.",
  "Stop paying lakhs just to format what your plant already logged.":
    "પ્લાન્ટે પહેલેથી લખેલું ફોર્મેટ કરવા લાખો ન આપો.",
  "Tell collection to stay local, or leave the score as it is.":
    "કલેક્શનને નજીક રહેવાનું કહો, અથવા સ્કોર જેમ છે તેમ રાખો.",
  "Think of carbon credits like a bank balance that grows when your plant captures methane.":
    "કાર્બન ક્રેડિટને બેંક બેલેન્સ ગણો — પ્લાન્ટ મિથેન પકડે ત્યારે વધે.",
  "This is where proof lives. Auditors can look — they cannot edit.":
    "પુરાવો અહીં રહે. ચેકર જોઈ શકે — ફેરફાર નહીં.",
  "This is your money. Call before the next truck leaves.":
    "આ તમારા પૈસા છે. આગલી ટ્રક નીકળે તે પહેલા ફોન કરો.",
  "This person is not on the book.": "આ વ્યક્તિ નોંધમાં નથી.",
  "This score decides how much buyers pay for your carbon. Improve it, earn more.":
    "આ સ્કોર કહે ખરીદનાર તમારા કાર્બન માટે કેટલા પૈસા આપે. સુધારો, વધુ કમાઓ.",
  "Use local dung": "સ્થાનિક ગોબર વાપરો",
  "Weighbridge OK + photo sealed": "વેબ્રિજ OK + ફોટો સીલ",
  "Weighing scale for the whole plant": "પૂરા પ્લાન્ટની તરાજુ",
  "What is running, what is waiting, and what failed the check — not a list of every job.":
    "શું ચાલે, શું રાહ જુએ, અને શું ચેકમાં નાપાસ — દરેક કામની યાદી નહીં.",
  "What makes the score": "સ્કોર શું બનાવે",
  "Who can open what, plant basics, and your Urja plan price.":
    "કોણ શું ખોલે, પ્લાન્ટની મૂળ વાત, અને ઉર્જા પ્લાનની કિંમત.",
  "Who is missing, which job is late, whose leave still needs a yes.":
    "કોણ ખૂટે, કયું કામ મોડું, કોની રજાને હજુ હા જોઈએ.",
  "Who to pay so the next truck still comes — not a list of every supplier.":
    "આગલી ટ્રક આવે તે માટે કોને પૈસા — દરેક સપ્લાયરની યાદી નહીં.",
  "Will production stop? What arrived short? What still needs your tick.":
    "ઉત્પાદન રોકાશે? શું ઓછું આવ્યું? શુંને હજુ તમારી ટિક જોઈએ.",
  "100% dung": "૧૦૦% ગોબર",
  "50% dung · 50% agri residue": "૫૦% ગોબર · ૫૦% ખેત અવશેષ",
  "65% dung · 25% napier · 10% residue": "૬૫% ગોબર · ૨૫% નેપિયર · ૧૦% અવશેષ",
  "70% dung · 30% napier": "૭૦% ગોબર · ૩૦% નેપિયર",
  "A bag batch exists only when Production logs it here.":
    "બેગ બેચ ત્યારે જ જ્યારે ઉત્પાદન અહીં લખે.",
  "A job exists only when someone on this desk assigns a person from Staff.":
    "કામ ત્યારે જ જ્યારે આ ડેસ્ક સ્ટાફમાંથી વ્યક્તિ આપે.",
  "Afternoon purification has a hole. Move someone from morning or hold the line.":
    "બપોરના શુદ્ધિકરણમાં છિદ્ર છે. સવારમાંથી કોઈને ખસેડો અથવા લાઈન રોકો.",
  "Better score = more ₹ for the same carbon. Lower number is better.":
    "સારો સ્કોર = એ જ કાર્બન માટે વધુ ₹. નીચો આંકડો સારો.",
  "Biosafety / slurry handling certificate": "બાયોસેફ્ટી / સ્લરી હેન્ડલિંગ સર્ટિફિકેટ",
  "Bank locker with a clear chain": "સાફ સાંકળવાળું બેંક લોકર",
  "Certificate required for offtake invoice": "ઑફટેક બિલ માટે સર્ટિફિકેટ જોઈએ",
  "CGD injection meter calibration": "CGD ઇન્જેક્શન મીટર કેલિબ્રેશન",
  "Chase dates live on Sales — not a separate calendar.":
    "વસૂલીની તારીખ વેચાણ પર — અલગ કેલેન્ડર નહીં.",
  "Chase that unpaid lot, or log a new batch if bags are ready.":
    "બાકી લોટ વસૂલો, અથવા બેગ તૈયાર હોય તો નવી બેચ લખો.",
  "Compare every site side by side — which one is strong, which one needs help.":
    "દરેક સાઈટ બાજુમાં મૂકો — કઈ મજબૂત, કઈને મદદ જોઈએ.",
  "Consent to Operate renewal": "ચાલુ રાખવાની મંજૂરી રિન્યુ",
  "Consultant in a button": "બટનમાં કન્સલ્ટન્ટ",
  "Did the dung that went in match the gas that came out? Auditors check this.":
    "અંદર ગયેલું ગોબર બહાર આવેલા ગેસ સાથે મળે? ચેકર આ જુએ.",
  "Dirty gas becomes saleable CBG here. If recovery is low, you are throwing money away.":
    "ગંદો ગેસ અહીં વેચાય તેવો CBG બને. રિકવરી ઓછી હોય તો પૈસા ફેંકો છો.",
  "Factory CCTV for data": "ડેટા માટે ફેક્ટરી CCTV",
  "Heartbeat check for hardware": "હાર્ડવેરની ધબકાર તપાસ",
  "LOI offtake volume — monthly check": "LOI ઑફટેક જથ્થો — મહિનાની તપાસ",
  "Maharashtra Pollution Control Board": "મહારાષ્ટ્ર પ્રદૂષણ નિયંત્રણ બોર્ડ",
  "Need ≥ 1,000 kg/day average CBG to IOCL / CGD":
    "IOCL / CGD માટે સરેરાશ ≥ ૧,૦૦૦ કિગ્રા/દિવસ CBG જોઈએ",
  "Passbook for climate money": "આબોહવા પૈસાની પાસબુક",
  "Price tag for your carbon": "તમારા કાર્બનની કિંમત ટેગ",
  "Renew before slurry sales peak season": "સ્લરી વેચાણની મોસમ પહેલા રિન્યુ",
  "Scoreboard for all your plants": "તમારા બધા પ્લાન્ટનું સ્કોરબોર્ડ",
  "Spell-check for plant truth": "પ્લાન્ટની સચ્ચાઈની સ્પેલ-ચેક",
  "Subsidy tranche 2 — plant photos + logs": "સબસિડી ટ્રાન્ચ ૨ — પ્લાન્ટ ફોટો + લોગ",
  "Upload commissioning evidence pack": "કમિશનિંગ પુરાવા પેક અપલોડ",
  "Which tank makes more gas?": "કઈ ટાંકી વધુ ગેસ બનાવે?",
  "Which mix won this quarter?": "આ ત્રિમાસમાં કયું મિક્સ જીત્યું?",
  "Call to collect, or send another truck anyway.":
    "વસૂલવા ફોન કરો, અથવા છતાં બીજી ટ્રક મોકલો.",
  "cut napier. Recheck pH at 2pm.": "નેપિયર કાપો. બપોરે ૨ વાગ્યે pH ફરી જુઓ.",
  "D2 mix:": "D2 મિક્સ:",
  "Extra — only if you choose it": "વધારાનું — જો તમે પસંદ કરો",
  "Who can open what": "કોણ શું ખોલે",
};

/** Whole-word leftovers after phrase replace. No articles; keys must be unique. */
export const WORDS: Record<string, string> = {
  truck: "ટ્રક",
  trucks: "ટ્રક",
  money: "પૈસા",
  plant: "પ્લાન્ટ",
  plants: "પ્લાન્ટ",
  tank: "ટાંકી",
  tanks: "ટાંકી",
  gas: "ગેસ",
  dung: "ગોબર",
  napier: "નેપિયર",
  residue: "અવશેષ",
  mix: "મિક્સ",
  staff: "સ્ટાફ",
  salary: "પગાર",
  pay: "પૈસા આપો",
  paid: "ચૂકવ્યું",
  unpaid: "બાકી",
  bill: "બિલ",
  bills: "બિલ",
  stock: "સ્ટોક",
  store: "સ્ટોર",
  sales: "વેચાણ",
  sale: "વેચાણ",
  customer: "ગ્રાહક",
  customers: "ગ્રાહક",
  supplier: "સપ્લાયર",
  suppliers: "સપ્લાયર",
  farmer: "ખેડૂત",
  farmers: "ખેડૂત",
  driver: "ડ્રાઈવર",
  drivers: "ડ્રાઈવર",
  trip: "ટ્રિપ",
  trips: "ટ્રિપ",
  job: "કામ",
  jobs: "કામ",
  leave: "રજા",
  lab: "લેબ",
  sample: "નમૂનો",
  samples: "નમૂના",
  photo: "ફોટો",
  photos: "ફોટો",
  paper: "કાગળ",
  papers: "કાગળ",
  proof: "પુરાવો",
  owner: "માલિક",
  today: "આજે",
  yesterday: "ગઈકાલે",
  tomorrow: "કાલે",
  month: "મહિનો",
  monthly: "મહિનાનું",
  week: "અઠવાડિયું",
  day: "દિવસ",
  days: "દિવસ",
  hour: "કલાક",
  hours: "કલાક",
  date: "તારીખ",
  dates: "તારીખ",
  due: "તારીખ",
  overdue: "મોડું",
  late: "મોડું",
  present: "હાજર",
  absent: "ગેરહાજર",
  waiting: "રાહ",
  pending: "બાકી",
  approved: "મંજૂર",
  rejected: "નામંજૂર",
  open: "ખોલો",
  close: "બંધ",
  closed: "બંધ",
  start: "શરૂ",
  stop: "રોકો",
  hold: "રોકો",
  allow: "હા",
  save: "સેવ",
  send: "મોકલો",
  call: "ફોન",
  collect: "વસૂલો",
  chase: "પાછા માગો",
  order: "ઓર્ડર",
  orders: "ઓર્ડર",
  weight: "વજન",
  tonne: "ટન",
  tonnes: "ટન",
  bag: "બેગ",
  bags: "બેગ",
  batch: "બેચ",
  lot: "લોટ",
  line: "લાઈન",
  floor: "ફ્લોર",
  desk: "ડેસ્ક",
  card: "કાર્ડ",
  name: "નામ",
  phone: "ફોન",
  email: "ઈમેઈલ",
  village: "ગામ",
  city: "શહેર",
  map: "નકશો",
  route: "રસ્તો",
  gate: "ગેટ",
  pad: "પેડ",
  feed: "ખોરાક",
  slurry: "સ્લરી",
  fertilizer: "ખાતર",
  credit: "ક્રેડિટ",
  credits: "ક્રેડિટ",
  carbon: "કાર્બન",
  sensor: "સેન્સર",
  sensors: "સેન્સર",
  machine: "મશીન",
  machines: "મશીન",
  meter: "મીટર",
  warning: "ચેતવણી",
  warnings: "ચેતવણી",
  alert: "ખતરો",
  watch: "જુઓ",
  status: "સ્થિતિ",
  score: "સ્કોર",
  value: "કિંમત",
  price: "ભાવ",
  fee: "ફી",
  hole: "છિદ્ર",
  holes: "છિદ્ર",
  yes: "હા",
  no: "ના",
  and: "અને",
  or: "અથવા",
  for: "માટે",
  from: "થી",
  with: "સાથે",
  without: "વગર",
  your: "તમારું",
  my: "મારું",
  this: "આ",
  that: "તે",
  these: "આ",
  those: "તે",
  is: "છે",
  are: "છે",
  was: "હતું",
  were: "હતા",
  not: "નહીં",
  still: "હજુ",
  already: "પહેલેથી",
  more: "વધુ",
  less: "ઓછું",
  extra: "વધારાનું",
  first: "પહેલું",
  next: "આગળ",
  last: "છેલ્લું",
  new: "નવું",
  old: "જૂનું",
  big: "મોટું",
  small: "નાનું",
  full: "પૂરું",
  empty: "ખાલી",
  short: "ઓછું",
  high: "ઊંચું",
  low: "નીચું",
  sick: "બીમાર",
  sour: "ખાટું",
  clean: "સાફ",
  dirty: "ગંદું",
  green: "લીલું",
  yellow: "પીળું",
  red: "લાલ",
  gold: "સોનેરી",
  person: "વ્યક્તિ",
  people: "લોકો",
  team: "ટીમ",
  company: "કંપની",
  factory: "ફેક્ટરી",
  office: "ઓફિસ",
  production: "ઉત્પાદન",
  inventory: "સ્ટોક",
  finance: "પૈસા",
  reports: "રિપોર્ટ",
  settings: "સેટિંગ્સ",
  login: "લોગિન",
  logout: "બહાર",
  password: "પાસવર્ડ",
  search: "શોધો",
  find: "શોધો",
  show: "બતાવો",
  hide: "છુપાવો",
  view: "જુઓ",
  edit: "ફેરફાર",
  add: "ઉમેરો",
  delete: "કાઢો",
  upload: "અપલોડ",
  download: "ડાઉનલોડ",
  print: "પ્રિન્ટ",
  back: "પાછા",
  continue: "આગળ",
  done: "પૂરું",
  cancel: "રદ",
  confirm: "પુષ્ટિ",
  loading: "ખુલે છે",
  live: "લાઈવ",
  online: "ઓનલાઈન",
  offline: "ઑફલાઈન",
  silent: "શાંત",
  weak: "નબળું",
  strong: "મજબૂત",
  ready: "તૈયાર",
  failed: "નાપાસ",
  pass: "પાસ",
  fail: "નાપાસ",
  quality: "ક્વોલિટી",
  test: "ટેસ્ટ",
  tests: "ટેસ્ટ",
  result: "રિઝલ્ટ",
  results: "રિઝલ્ટ",
  flag: "ફ્લેગ",
  gap: "ગેપ",
  gaps: "ગેપ",
  data: "ડેટા",
  number: "આંકડો",
  numbers: "આંકડા",
  rupee: "રૂપિયો",
  rupees: "રૂપિયા",
  lakh: "લાખ",
  months: "મહિના",
  weeks: "અઠવાડિયા",
  August: "ઓગસ્ટ",
  July: "જુલાઈ",
  Sep: "સપ્ટે",
  Sept: "સપ્ટે",
  September: "સપ્ટેમ્બર",
  Jan: "જાન્યુ",
  Feb: "ફેબ્રુ",
  Mar: "માર્ચ",
  Apr: "એપ્રિલ",
  May: "મે",
  Jun: "જૂન",
  Oct: "ઑક્ટો",
  Nov: "નવે",
  Dec: "ડિસે",
  Monday: "સોમવાર",
  Tuesday: "મંગળવાર",
  Wednesday: "બુધવાર",
  Thursday: "ગુરુવાર",
  Friday: "શુક્રવાર",
  Saturday: "શનિવાર",
  Sunday: "રવિવાર",
  morning: "સવાર",
  afternoon: "બપોર",
  night: "રાત",
  shift: "શિફ્ટ",
  attend: "હાજરી",
  attendance: "હાજરી",
  advance: "એડવાન્સ",
  incentive: "ઇન્સેન્ટિવ",
  discount: "છૂટ",
  buyer: "ખરીદનાર",
  invoice: "બિલ",
  invoices: "બિલ",
  offtake: "ઑફટેક",
  subsidy: "સબસિડી",
  license: "લાઈસન્સ",
  renewal: "રિન્યુઅલ",
  auditor: "ચેકર",
  admin: "એડમિન",
  accountant: "એકાઉન્ટન્ટ",
  employee: "કર્મચારી",
  operator: "ઓપરેટર",
  purification: "શુદ્ધિકરણ",
  cylinder: "સિલિન્ડર",
  cylinders: "સિલિન્ડર",
  weighbridge: "વેબ્રિજ",
  grass: "ઘાસ",
  blend: "મિક્સ",
  recipe: "રેસીપી",
  yield: "ઉપજ",
  recovery: "રિકવરી",
  leak: "લીક",
  filter: "ફિલ્ટર",
  cleaner: "ક્લીનર",
  pipe: "પાઈપ",
  diesel: "ડીઝલ",
  power: "પાવર",
  bank: "બેંક",
  pocket: "જેબ",
  tick: "ટિક",
  ticks: "ટિક",
  spend: "ખર્ચ",
  spends: "ખર્ચ",
  crash: "ક્રેશ",
  souring: "સાવરિંગ",
  acids: "એસિડ",
  acid: "એસિડ",
  heat: "ગરમી",
  probe: "પ્રોબ",
  fitter: "ફિટર",
  hire: "ભરતી",
  punch: "પંચ",
  muster: "મસ્ટર",
  payslip: "પગાર સ્લિપ",
  extras: "વધારો",
  basic: "મૂળ",
  net: "હાથ પર",
  gross: "કુલ",
  cut: "કાપ",
  cuts: "કાપ",
  deduct: "કાપ",
  type: "લખો",
  typed: "લખ્યું",
  log: "નોંધ",
  logged: "નોંધાયું",
  book: "નોંધ",
  change: "ફેરફાર",
  diary: "ડાયરી",
  calendar: "કેલેન્ડર",
  reminder: "યાદ",
  ping: "પિંગ",
  thread: "થ્રેડ",
  message: "મેસેજ",
  talk: "વાત",
  chat: "વાત",
  pin: "પિન",
  gps: "GPS",
  km: "કિમી",
  kg: "કિગ્રા",
  t: "ટન",
  vs: "વિ",
  per: "દીઠ",
  each: "દરેક",
  all: "બધું",
  only: "ફક્ત",
  also: "પણ",
  before: "પહેલા",
  after: "પછી",
  until: "ત્યાં સુધી",
  if: "જો",
  then: "પછી",
  when: "જ્યારે",
  where: "ક્યાં",
  who: "કોણ",
  what: "શું",
  which: "કયું",
  why: "શા માટે",
  how: "કેવી રીતે",
  please: "કૃપા કરીને",
  thank: "આભાર",
  hello: "નમસ્તે",
  namaste: "નમસ્તે",
  boss: "માલિક",
  seat: "સીટ",
  page: "પેજ",
  pages: "પેજ",
  screen: "સ્ક્રીન",
  button: "બટન",
  box: "બોક્સ",
  table: "ટેબલ",
  list: "યાદી",
  pack: "પેક",
  locker: "લોકર",
  cupboard: "અલમારી",
  register: "રજિસ્ટર",
  registers: "રજિસ્ટર",
  app: "એપ",
  plan: "પ્લાન",
  once: "એક વાર",
  free: "મફત",
  look: "જુઓ",
  see: "જુઓ",
  decide: "નક્કી કરો",
  keep: "રાખો",
  stay: "રહો",
  come: "આવો",
  go: "જાઓ",
  left: "છોડ્યું",
  arrived: "આવ્યું",
  finished: "પૂરું",
  running: "ચાલે છે",
  blocked: "બ્લોક",
  stuck: "અટકેલું",
  wasted: "વેડફાયું",
  waste: "વેડફાટ",
  dark: "રાત",
  light: "દિવસ",
};
