export const INVENTORY = [
  {
    id: "SKU-DUNG",
    name: "Cattle dung (pit)",
    unit: "t",
    onHand: 86.4,
    reorderAt: 40,
    dailyUse: 12,
    lastIn: "2026-08-16",
  },
  {
    id: "SKU-NAP",
    name: "Napier grass",
    unit: "t",
    onHand: 12.4,
    reorderAt: 15,
    dailyUse: 8,
    lastIn: "2026-08-16",
  },
  {
    id: "SKU-RES",
    name: "Agri residue",
    unit: "t",
    onHand: 31.0,
    reorderAt: 20,
    dailyUse: 6,
    lastIn: "2026-08-15",
  },
  {
    id: "SKU-BAG",
    name: "FOM empty bags",
    unit: "pcs",
    onHand: 2400,
    reorderAt: 1000,
    dailyUse: 310,
    lastIn: "2026-08-10",
  },
];

export const WORKFORCE = [
  {
    id: "E-01",
    name: "Suresh Patil",
    role: "Shift in-charge",
    today: "present" as const,
    inTime: "06:02",
    outTime: "14:08",
    monthPresent: 22,
    monthAbsent: 1,
  },
  {
    id: "E-02",
    name: "Anita Deshmukh",
    role: "Weighbridge",
    today: "present" as const,
    inTime: "06:15",
    outTime: "14:12",
    monthPresent: 21,
    monthAbsent: 2,
  },
  {
    id: "E-03",
    name: "Ravi More",
    role: "Digester helper",
    today: "late" as const,
    inTime: "07:40",
    outTime: "—",
    monthPresent: 19,
    monthAbsent: 4,
  },
  {
    id: "E-04",
    name: "Kiran Jadhav",
    role: "Purification",
    today: "absent" as const,
    inTime: "—",
    outTime: "—",
    monthPresent: 20,
    monthAbsent: 3,
  },
  {
    id: "E-05",
    name: "Meena Pawar",
    role: "Lab sample",
    today: "present" as const,
    inTime: "06:30",
    outTime: "14:05",
    monthPresent: 23,
    monthAbsent: 0,
  },
  {
    id: "E-06",
    name: "Ganesh Patil",
    role: "Driver",
    today: "present" as const,
    inTime: "05:20",
    outTime: "—",
    monthPresent: 22,
    monthAbsent: 1,
  },
  {
    id: "E-07",
    name: "Sandeep Shinde",
    role: "Driver",
    today: "present" as const,
    inTime: "05:00",
    outTime: "—",
    monthPresent: 21,
    monthAbsent: 2,
  },
  {
    id: "E-08",
    name: "Kiran Pawar",
    role: "Driver",
    today: "present" as const,
    inTime: "06:10",
    outTime: "—",
    monthPresent: 20,
    monthAbsent: 2,
  },
];

export const DOC_VAULT = [
  {
    id: "DOC-01",
    title: "Vendor agreement — Ganesh Transport",
    type: "Contract",
    date: "2026-01-12",
  },
  {
    id: "DOC-02",
    title: "Fire NOC scan",
    type: "Safety",
    date: "2025-11-03",
  },
  {
    id: "DOC-03",
    title: "GST invoice pack — Jul 2026",
    type: "Finance",
    date: "2026-08-01",
  },
  {
    id: "DOC-04",
    title: "Staff PF challan",
    type: "HR",
    date: "2026-08-05",
  },
];
